# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HumblskillsPre < Formula
  desc "Pre-release (develop) build of humblskills. Does not replace the stable formula."
  homepage "https://github.com/jjfantini/humblSKILLS"
  version "2.52.0-pre.3"
  license "CC-BY-4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjfantini/humblSKILLS/releases/download/v2.52.0-pre.3/humblskills_2.52.0-pre.3_macos_amd64.tar.gz"
      sha256 "92373971819dc6798bef5099e32ed07f595b434405bc90330f23e9b92aba2673"

      define_method(:install) do
        bin.install "humblskills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/humblSKILLS/releases/download/v2.52.0-pre.3/humblskills_2.52.0-pre.3_macos_arm64.tar.gz"
      sha256 "23225cdf9dc491b4e38d0deaaf7c9e3dca69cf7c503c0238849d1e214c60127f"

      define_method(:install) do
        bin.install "humblskills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjfantini/humblSKILLS/releases/download/v2.52.0-pre.3/humblskills_2.52.0-pre.3_linux_amd64.tar.gz"
      sha256 "481d3ac42cd1869f746f77161dbf342431956b2a6abb3d2073ffd2aa906aea60"
      define_method(:install) do
        bin.install "humblskills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjfantini/humblSKILLS/releases/download/v2.52.0-pre.3/humblskills_2.52.0-pre.3_linux_arm64.tar.gz"
      sha256 "0b8ff109661810a9d4dbd0fd9a524bac575451ca134516e0814596b7c6f06445"
      define_method(:install) do
        bin.install "humblskills"
      end
    end
  end

  conflicts_with "humblskills"

  test do
    system "#{bin}/humblskills", "version"
  end
end
