# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HumblskillsPre < Formula
  desc "Pre-release (develop) build of humblskills. Does not replace the stable formula."
  homepage "https://github.com/jjfantini/humblSKILLS"
  version "2.52.0-pre"
  license "CC-BY-4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jjfantini/humblSKILLS/releases/download/v2.52.0-pre/humblskills_2.52.0-pre_macos_amd64.tar.gz"
      sha256 "f9abd702c67c033ed2b8e6eee492145090114f87fef86ff8bcec9b174a33a353"

      define_method(:install) do
        bin.install "humblskills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/humblSKILLS/releases/download/v2.52.0-pre/humblskills_2.52.0-pre_macos_arm64.tar.gz"
      sha256 "f9edf6e59a676033f1c0a672729b61ce32915a636e8770d0f1728656021a1402"

      define_method(:install) do
        bin.install "humblskills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjfantini/humblSKILLS/releases/download/v2.52.0-pre/humblskills_2.52.0-pre_linux_amd64.tar.gz"
      sha256 "431a0a934d366332219d74eeda87b08f50a9cbf3c5e2275680af35f9abd586fe"
      define_method(:install) do
        bin.install "humblskills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjfantini/humblSKILLS/releases/download/v2.52.0-pre/humblskills_2.52.0-pre_linux_arm64.tar.gz"
      sha256 "36848e3dfedaf2c34037b874b8c19125dbc731d80c4e63af80d49e0b41ec2e11"
      define_method(:install) do
        bin.install "humblskills"
      end
    end
  end

  conflicts_with "humblskills"

  test do
    system "#{bin}/humblskills", "version"
  end
end
