# typed: false
# frozen_string_literal: true

# This file is generated by scripts/publish-formulae.sh — do not edit by hand.
class PindexLite < Formula
  desc "pindex (pure-Go, portable build — Apache-2.0, no MuPDF/cgo)"
  homepage "https://github.com/jjfantini/pindex"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.5.0/pindex-lite_0.5.0_darwin_arm64.tar.gz"
      sha256 "ddf4b2b6fdc38734445c5b3aaa907d3037ef0e2a4bfad7dd2475b921197c49fc"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.5.0/pindex-lite_0.5.0_darwin_amd64.tar.gz"
      sha256 "b468de12cbb63f638e0993b29d3f829838f6e109af453af36b081635353e5423"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.5.0/pindex-lite_0.5.0_linux_arm64.tar.gz"
      sha256 "d41bf297420db10558386fe247021242b461eaded74104008727c0a790f099fa"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.5.0/pindex-lite_0.5.0_linux_amd64.tar.gz"
      sha256 "75411a705cc262cd840003096bf4dc9fb7272e3c52f2cf84f01f194001815538"
    end
  end

  def install
    bin.install "pindex-lite"
  end

  def caveats
    <<~EOS
      pindex-lite is the pure-Go build with no MuPDF extractor compiled in.
      Set `extractor: purego` in your pindex config; the `mupdf` backend is
      unavailable in this build (it returns a clear error if selected).
    EOS
  end
  test do
    system "#{bin}/pindex-lite", "--version"
  end
end
