# typed: false
# frozen_string_literal: true

# This file is generated by scripts/publish-formulae.sh — do not edit by hand.
class PindexLite < Formula
  desc "pindex (pure-Go, portable build — Apache-2.0, no MuPDF/cgo)"
  homepage "https://github.com/jjfantini/pindex"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.7.0/pindex-lite_0.7.0_darwin_arm64.tar.gz"
      sha256 "ea3483ada740abca9ed3b6c6ba20a4334531128c1b1ca1092832130360ca5813"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.7.0/pindex-lite_0.7.0_darwin_amd64.tar.gz"
      sha256 "69a2e59e862e788c264640403290d8471ca89f33f965d97411806905dd8130f0"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.7.0/pindex-lite_0.7.0_linux_arm64.tar.gz"
      sha256 "92c1a6e6abfd3ffd1f224d521a398f7ed28b672a01e8b2d5b8db7cabaf68181c"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.7.0/pindex-lite_0.7.0_linux_amd64.tar.gz"
      sha256 "52410edc42970e83361c31ae818fbe536499191bf4cf7bbf05f81d3fed0a48c9"
    end
  end

  def install
    bin.install "pindex-lite"
  end

  def caveats
    <<~EOS
      pindex-lite is the pure-Go build with no MuPDF extractor compiled in.
      Set `extractor: purego` in your pindex config; the `mupdf` backend is
      unavailable in this build (it returns a clear error if selected).
    EOS
  end
  test do
    system "#{bin}/pindex-lite", "--version"
  end
end
