# typed: false
# frozen_string_literal: true

# This file is generated by scripts/publish-formulae.sh — do not edit by hand.
class Pindex < Formula
  desc "Vectorless reasoning-RAG engine in Go — hierarchical tree index over PDFs, cited answers"
  homepage "https://github.com/jjfantini/pindex"
  version "0.6.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.6.0/pindex_0.6.0_darwin_arm64.tar.gz"
      sha256 "429b2ac047dce2405fef809fbb4b6c6bbd2c99f6bb05d7ea296cc10f713ebb95"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.6.0/pindex_0.6.0_darwin_amd64.tar.gz"
      sha256 "1c36fe0ce5e812223c0e77f6de1e1c339d10ed721d0218983b283e8b62df4b06"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.6.0/pindex_0.6.0_linux_arm64.tar.gz"
      sha256 "efc89ce701d88b173dbccf991f352bc2f68a6ba8446e51d145cd38f17790e479"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.6.0/pindex_0.6.0_linux_amd64.tar.gz"
      sha256 "fd7a94883626ab481d7e8e19db95f97ea959f363680e9bd0ee118ae725992bee"
    end
  end

  def install
    bin.install "pindex"
  end

  test do
    system "#{bin}/pindex", "--version"
  end
end
