# typed: false
# frozen_string_literal: true

# This file is generated by scripts/publish-formulae.sh — do not edit by hand.
class PindexLite < Formula
  desc "pindex (pure-Go, portable build — Apache-2.0, no MuPDF/cgo)"
  homepage "https://github.com/jjfantini/pindex"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.1.1/pindex-lite_0.1.1_darwin_arm64.tar.gz"
      sha256 "3b0c015f91aadb5c17d3adf4bf410367a312f2957fe252fd83051f214f954fc1"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.1.1/pindex-lite_0.1.1_darwin_amd64.tar.gz"
      sha256 "2a2c1997a442c57c069d4facd9049329352f30ba530ab265f3483af55f193e1f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.1.1/pindex-lite_0.1.1_linux_arm64.tar.gz"
      sha256 "4027da19bcd8c94b43b3017b3748113f192c1113fa0f35c0a15157ef2345213a"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.1.1/pindex-lite_0.1.1_linux_amd64.tar.gz"
      sha256 "b36747ba3688ced1f70b5edccb675269be3e7ba9f21d0ad89e87731384003de9"
    end
  end

  def install
    bin.install "pindex-lite"
  end

  def caveats
    <<~EOS
      pindex-lite is the pure-Go build with no MuPDF extractor compiled in.
      Set `extractor: purego` in your pindex config; the `mupdf` backend is
      unavailable in this build (it returns a clear error if selected).
    EOS
  end
  test do
    system "#{bin}/pindex-lite", "--version"
  end
end
