# typed: false
# frozen_string_literal: true

# This file is generated by scripts/publish-formulae.sh — do not edit by hand.
class Pindex < Formula
  desc "Vectorless reasoning-RAG engine in Go — hierarchical tree index over PDFs, cited answers"
  homepage "https://github.com/jjfantini/pindex"
  version "0.2.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.2.0/pindex_0.2.0_darwin_arm64.tar.gz"
      sha256 "a6f51ffb6857014a22f29499a031841fa88efd054be7ed74bd1ec9c59f64d771"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.2.0/pindex_0.2.0_darwin_amd64.tar.gz"
      sha256 "54cbaa17d3d7f6e6c62478c75e4799d086fe59450acbaaf1527e11de2bff69e3"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/jjfantini/pindex/releases/download/v0.2.0/pindex_0.2.0_linux_arm64.tar.gz"
      sha256 "9737089d6018f2edcb208907f81dd29b3113fccb2a4f0d01ea9c996c34ad9c82"
    else
      url "https://github.com/jjfantini/pindex/releases/download/v0.2.0/pindex_0.2.0_linux_amd64.tar.gz"
      sha256 "b594329c3ae88c4a1f533997714a07e9278fb64deaca0cc526ebeaeca15040f9"
    end
  end

  def install
    bin.install "pindex"
  end

  test do
    system "#{bin}/pindex", "--version"
  end
end
